[package]
name = "tun-dev-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
net-route = "0.2.5"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
pnet = "0.34.0"