name: Publish release

on:
  push:
    branches: ['main']
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  linux-release:
    name: Release Linux x86_64
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: tun-route-daemon
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository    
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies        
      - name: Build-musl
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target x86_64-unknown-linux-musl --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ PACKAGE_NAME }}-linux-x86_64"

permissions:
  contents: write